- name: add docker repo
  command:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: yum install docker/docker compose and update cache
  yum:
    update_cache: true 
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: run docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Add the user 'ec2-user' appending the group 'docker'
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: install docker compose
  become: true
  shell: 
    cmd: curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

- name: give docker-compose executable permission
  become: true
  file:
    path: /usr/local/bin/docker-compose
    mode: a+x

- name: export docker-compose
  become: true
  shell: 
    cmd: export PATH="$PATH":/usr/local/bin

- name: source docker-compose
  become: true
  shell:
    cmd: source /root/.bashrc