#install docker
- name: apt install tools before docker install
  apt:
    update_cache: yes
    name:
    - ca-certificates
    - gnupg
    - lsb-release

- name: add docker repo directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: add docker official GPG key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg

- name: set up docker repo
  shell:
    cmd: echo  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: apt install docker/docker compose and update cache
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
      - docker-compose-plugin

- name: Add the user 'ec2-user' appending the group 'docker'
  user:
    name: ubuntu
    groups: docker
    append: yes