---
- name: Docker Install
  hosts: bingobingo-rel-srv-01
  become: true

  roles:
    - { role: docker_awslinux, when: "ansible_os_family == 'RedHat'" }
    - { role: docker_ubuntu, when: "ansible_os_family == 'Debian'" } 
    #- { role: docker_redhat, when: "ansible_os_family == 'RedHat'" }

