- name: install docker
  command:
    cmd: amazon-linux-extras install docker -y

- name: run docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Create docker cli folder
  file: 
    path: /root/.docker/cli-plugins
    state: directory

- name: check docker compose plugin exists
  stat:
    path: /root/.docker/cli-plugins/docker-compose
  register: result

- name: install docker compose plugin
  command:
    cmd:  curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o /root/.docker/cli-plugins/docker-compose
  when: not result.stat.exists

- name: excutable permission for docker compose
  file:
    path: /root/.docker/cli-plugins/docker-compose
    mode: +x
  when: not result.stat.exists

- name: Add the user 'ec2-user' appending the group 'docker'
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: install docker-compose
  become: true
  shell: 
    cmd: curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

- name: give docker-compose executable permission
  become: true
  file:
    path: /usr/local/bin/docker-compose
    mode: a+x

- name: export docker-compose
  become: true
  shell: 
    cmd: export PATH="$PATH":/usr/local/bin

- name: source docker-compose
  become: true
  shell:
    cmd: source /root/.bashrc